server:
  port: ${PORT}

spring:
  application:
    name: notes

  datasource:
    url: jdbc:h2:file:/app/data/noteedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: ${DB_USER}
    password: ${DB_PASS}

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret-key: ${JWT_SECRET}
  token_exp: ${TOKEN_EXP:3600000}
  refresh_token_exp: ${REFRESH_EXP:86400000}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /api-docs
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    disable-swagger-default-url: true
    title: "Notes API Documentation"
  show-actuator: true


rate-limit:
  auth:
    capacity: 5
    refill: 5
    duration: 1m
  api:
    capacity: 100
    refill: 100
    duration: 1m
  notes-create:
    capacity: 20
    refill: 20
    duration: 1m
  notes-update:
    capacity: 30
    refill: 30
    duration: 1m

logging:
  level:
    com.gideon.notes: DEBUG